cmake_minimum_required(VERSION 3.8)
project(robot_virtual_fence)

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)

add_executable(virtual_fence_node src/virtual_fence.cpp)
ament_target_dependencies(virtual_fence_node
  rclcpp
  moveit_ros_planning_interface
)

install(TARGETS virtual_fence_node
  DESTINATION lib/${PROJECT_NAME})

install(DIRECTORY config launch
  DESTINATION share/${PROJECT_NAME})

ament_package()

