# 请求部分
uint8 working_mode                      # 机械臂工作模式
std_msgs/Float64MultiArray gripper_goal               # 夹爪目标状态
std_msgs/Float64MultiArray joint_angles_goal          # 关节目标位置
std_msgs/Float64MultiArray arm_pose_goal              # 机械臂目标姿态
uint8[] gripper_data                    #夹爪原生数据
uint8   gripper_type                    #夹爪类型
uint8   joint_idx                       #关节序号
uint8   vel_dir                         #转动方向
robot_interfaces/GenericMotorParameter usr_param      #用户配置参数
std_msgs/Float64MultiArray motion_config               # 速度配置
---
# 响应部分
bool success
std_msgs/Float64MultiArray cur_joint_angles          # 关节目标位置
std_msgs/Float64MultiArray cur_pos                   # 当前位姿
